tproxy-port: 7895
redir-port: 7892
port: 7890
socks-port: 7891
mixed-port: 7893
bind-address: "*"
mode: rule
allow-lan: true
unified-delay: true
log-level: info
external-controller: 0.0.0.0:9999
external-ui: yacd-gh-pages
ipv6: false
secret: ''
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.0/8
  use-hosts: true
  listen: 0.0.0.0:1053
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://dns.google/dns-query
  - https://cloudflare-dns.com/dns-query
  - tls://1.1.1.1:853
  - tls://8.8.8.8:853
  fallback-filter:
    geoip: false
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
    - "+.whatsaap.net"
    - "+.itt9.com"
proxies:
  - name: SERVER VN 01
    server: 103.178.228.105
    port: 80
    type: vmess
    uuid: cbc3ba66-e381-4251-9031-a8d0c89965f4
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    network: ws
    ws-opts:
      path: /GoiFree_4ghatde.com
      headers:
        Host: 4ghatde.akamaized.net
    udp: true
  - name: SERVER VN 02
    server: 221.132.33.139
    port: 80
    type: vmess
    uuid: bcb3ed03-7bf5-4bd8-929e-a5c83107ae56
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    network: ws
    ws-opts:
      path: /sos4g.xyz
      headers:
        Host: 4ghatde.akamaized.net
    udp: true
  - name: SERVER VN 03
    server: 103.178.228.107
    port: 80
    type: vmess
    uuid: cbc3ba66-e381-4251-9031-a8d0c89965f4
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    network: ws
    ws-opts:
      path: /GoiFree_4ghatde.com
      headers:
        Host: 4ghatde.akamaized.net
    udp: true
  - name: SERVER VN 04
    server: 103.178.228.100
    port: 80
    type: vmess
    uuid: cbc3ba66-e381-4251-9031-a8d0c89965f4
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    network: ws
    ws-opts:
      path: /GoiFree_4ghatde.com
      headers:
        Host: 4ghatde.akamaized.net
    udp: true
  - name: SERVER HK 01
    server: hk1.fuzzyng.com
    port: 80
    type: vmess
    uuid: a8b87632-c428-4480-a443-0dd875704db4
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    network: ws
    ws-opts:
      path: /fuzzyng?ed=2048
      headers:
        Host: 4ghatde.akamaized.net
  - name: SERVER VN 05
    server: 103.161.176.117
    port: 80
    type: vmess
    uuid: 4bf285db-9258-425c-a137-3cb82231d70c
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    network: ws
    ws-opts:
      path: /
      headers:
        Host: 4ghatde.akamaized.net       
  - name: Singapore 01
    server: 45.118.132.10
    port: 80
    type: vmess
    uuid: 4bf285db-9258-425c-a137-3cb82231d70c
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    network: ws
    ws-opts:
      path: /
      headers:
        Host: 4ghatde.akamaized.net   
  - name: Singapore 02
    server: 167.172.71.221
    port: 80
    type: vmess
    uuid: 4bf285db-9258-425c-a137-3cb82231d70c
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    network: ws
    ws-opts:
      path: /
      headers:
        Host: 4ghatde.akamaized.net     
  - name: Singapore 03
    server: 172.104.60.243
    port: 80
    type: vmess
    uuid: 4bf285db-9258-425c-a137-3cb82231d70c
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: false
    network: ws
    ws-opts:
      path: /
      headers:
        Host: 4ghatde.akamaized.net                            
proxy-groups:
  - name: Duy Ola
    type: select
    proxies:
      - BEST PING
      - STREAMING
      - BROWSER
      - LOAD-BALANCE
      - SERVER VN 01
      - SERVER VN 02
      - SERVER VN 03
      - SERVER VN 04
      - SERVER VN 05
      - SERVER HK 01
      - Singapore 01
      - Singapore 02
      - Singapore 03
  - name: BEST PING
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - SERVER VN 01
      - SERVER VN 02
      - SERVER VN 03
      - SERVER VN 04
  - name: LOAD-BALANCE
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - SERVER VN 01
      - SERVER VN 02
      - SERVER VN 03
      - SERVER VN 04
  - name: STREAMING
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - SERVER VN 01
      - SERVER VN 02
  - name: BROWSER
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - SERVER VN 03
      - SERVER VN 04
rules:
  - DOMAIN-SUFFIX,v.whatsaap.net',DIRECT
  - DOMAIN-SUFFIX,g.whatsapp.net',DIRECT
  - DOMAIN-SUFFIX,e9.whatsaap.net',REJECT
  - DOMAIN-SUFFIX,c1.whatsaap.net',REJECT
  - DOMAIN-SUFFIX,cdn.whatsaap.net',DIRECT
  - DOMAIN-SUFFIX,c.whatsaap.net',DIRECT
  - DOMAIN-SUFFIX,ps.whatsaap.net',REJECT
  - DOMAIN-SUFFIX,bin-nokia.whatsaap.net',REJECT
  - DOMAIN-SUFFIX,www.whatsaap.net',DIRECT
  - DOMAIN-SUFFIX,s.whatsaap.net',DIRECT
  - DOMAIN-SUFFIX,m.whatsaap.net',REJECT
  - DOMAIN-SUFFIX,connectivitycheck.gstatic.com',DIRECT
  - DOMAIN-SUFFIX,play.googleapis.com',DIRECT
  - DOMAIN-SUFFIX,r4---sn-poqvn5u-n0cz.gvt1.com',REJECT
  - MATCH,Duy Ola
